
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcart-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petcart-store
  template:
    metadata:
      labels:
        app: petcart-store
    spec:
      containers:
        - name: petcart-store
          image: demo/petcart-store:latest
          ports:
            - containerPort: 3000
