apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: aws-observability
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_AT_RUNTIME:role/PetcartFluentBitRole
